# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "milky-way-terraform-state"
    dynamodb_table = "milky-way-terraform-locks"
    encrypt        = true
    key            = "environments/qa/terraform.tfstate"
    region         = "eu-south-2"
  }
}
