# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "aws_region" {
  description = "AWS region for resources"
  type        = string
}

variable "environment" {
  description = "Environment name (qa, prod)"
  type        = string
}

variable "project_name" {
  description = "Project name for tagging"
  type        = string
  default     = "milky-way-admin-panel"
}
